import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({message}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        Hi there from next app updated
        {message}
      </div>
    </>
  )
}
export async function getServerSideProps(){
  const response = await fetch('http://node-api:3000/api')
  const data = await response.json()
  return {
    props:{
      message: data.message,
    }
  }
}